### ISSUE TITLE
Calibration Error

### ISSUE THREAD

**Issue by lbussy** [lbussy/keg-cop#150]
I can’t calibrate the flow meter with the new devel firmware. I was able to successfully calibrate it in 1.0.0, however.

When I go to the calibrate page, Select Tap 9 (that’s the one and only I’m using since the 1-sided PCB made it easier), Config by volume, enter in some ounces measured, but don’t get a 0 to show up in the Pulses box until the flow starts. No pulses seen at all. 

_Originally posted by @rkhanso in https://github.com/lbussy/keg-cop/issues/51#issuecomment-1274170349_

**Comment by lbussy** [comment]
> don’t get a 0 to show up in the Pulses box until the flow starts. No pulses seen at all.

@rkhanso I want to be sure I understand this.  Why would it matter if the 0 shows up or not if you have not started flow?  The process for "By Volume" is:

1. Select "by volume"
2. Draw a sample of a known volume (e.g. 12 ounces)
3. (at this point pulses should register)
4. Enter "12" as the volume dispensed
5. The calculated PPU should be displayed

7. Enter "12" in the

**Comment by rkhanso** [comment]
Keg Cop quit working for me again. I think I'm going to have to go back to use CraftbeerPi3 for now on the Kegerator. I may try Bru Control in the future for all aspects of my brewing process.

From my memory though...
the 0 didn't pre-populate in the pulses box after I chose to calibrate, which then made it impossible to calibrate the flow meter. I knew this right away, because when there was a 0 in that box, I could change the number in the box. No zero in the box, the calibration number could not be entered and calibration was not possible.

**Comment by lbussy** [comment]
> Keg Cop quit working for me again.

In what way?  Mine has been running (without actually pulling beer) for two weeks or so.  I need to ficx the me not getting any beer part.

> From my memory though...

I'll have to try to set some time aside to work through that.  I'm still not sure if it's a documentation problem or a code problem.  Either way it's my problem I'm just not sure which.

**Comment by rkhanso** [comment]
It's been hit or miss whether I can get the web pages to load. It still seems to be rebooting randomly and losing configs. I have to go back in and reset the sensors, brewery name, etc.

Wouldn't you know.....right now it seems to be working.  

Eventually it'll stop and the kegerator won't be told to turn on and it'll be 68F in it again.

**Comment by rkhanso** [comment]
But now it just went berzerk again.  I clicked to go to the settings page and everything was reset - the 3 temp probes went to disabled. Control was then lost since there are no temps to control. 

The only thing that doesn't get reset is the Tap settings. They stick. Everything else is lost when "it" happens

**Comment by rkhanso** [comment]
One thing that I think would be helpful - some feedback after clicking the Update button on the settings page. I get no response that it accepted my changes. It just stays on that page and it looks like nothing happened until I leave it and go back (if it doesn't then reset itself again).

**Comment by lbussy** [comment]
> One thing that I think would be helpful - some feedback after clicking the Update button on the settings page. I get no response that it accepted my changes. It just stays on that page and it looks like nothing happened until I leave it and go back (if it doesn't then reset itself again).

There is - the button will disable and show a spinning icon while it is applied.  If it goes back to normal then it is applied.  If not, there will be an error banner.

**Comment by rkhanso** [comment]
I don't get a spinning circle. I get nothing confirming or denying the changes were saved or not. 

I still keep getting the sensors and control resetting very frequently. Sometimes within 20 seconds after setting them up. The Tap settings are still there, but the temp sensors all go disabled and the temp control is disabled.

I'm going to stick with CraftbeerPi3 on the Kegerator.

**Comment by rkhanso** [comment]
Is there a big difference in v 1.1.1 and 1.2.0-alpha?

 

The 1.1.1 version runs way better for me than the 1.2.0 version. 

 

1.2 is very slow between web pages or doesn’t load them at all. The ESP crashes.


1.1 is very stable and fast.

**Comment by lbussy** [comment]
> Is there a big difference in v 1.1.1 and 1.2.0-alpha?

Well, 1.2.0-Alpha is no longer supported; I released 1.2.0 officially, so if you are going to use a version, you should use that.

There are several changes between them, but the largest change is the core libraries from the manufacturer.  They are considerably larger and, by all accounts, do bring some additional quirks.

**Comment by rkhanso** [comment]
Are there big differences in the web server, web pages, file system or basic underlying systems? 

I ask, because I can run v 1.1.1 perfectly with fast web page response, no trouble loading pages for weeks so far.


But when on any of the 1.2 versions, the only web page that almost always opens is the home or about page. Often the temperature page doesn’t even show up in the menu and the setup page almost never loads (gets spinning circle). It still crashes frequently and I lose temp sensor settings, sometimes within a minute of setting them.

 

The reason I wanted v1.2 was to get the tower temp sensor to control the solenoid GPIO for a tower fan. I’ll gladly forget about that feature and just run 1.1.1 if that’s what it takes for the whole thing to be stable.

**Comment by lbussy** [comment]
Fix merged to devel, closing.
