### ISSUE TITLE
TaplistIO Tap numbers should always be non-zero

### ISSUE THREAD

**Issue by thorrak** [lbussy/keg-cop#18]
Found a bug in the taplistio implementation -- This line should be 

`if (flow.taps[tapid].taplistioTap <= 0 || flow.taps[tapid].taplistioTap > 255)`

https://github.com/lbussy/keg-cop/blob/3fa93d453e6b780db2a48922c8d48afb9d7ed087/src/taplistio.cpp#L48

**Comment by lbussy** [comment]
This could be fixed by the inclusion of a controller sequence (i.e. 1, 2, 3, etc.)  That way the tapid sent to TaplistIO could be factored from that.  I'm thinking:

``` cpp
tio_tapid = (tapid + 1) + ((controllerid-1) * 9)
```

If my math is right:
 * Controller 1 = Tap 1 -9
 * Controller 2 = Tap 10-18
 * ...

Are you able to finish this feature or should I look at it?

**Comment by thorrak** [comment]
If I'm interpreting your suggestion correctly, you're linking the taplistio tap ID to the Keg Cop tap IDs? I don't recommend that, as it requires very tight pairing between Keg Cop and Taplistio. What happens if someone wants to use Keg Cop for 3 of their taps, but -- IDK -- Kegtron for 2 of the others?

Personally I think TaplistIO tap ID should be an input, rather than derived.

**Comment by lbussy** [comment]
Pretty sure this is closed with the logic you added in [16c4152](https://github.com/lbussy/keg-cop/commit/16c4152c7aed8726b41904ad32f30487779b71a2).  Let me know if that's not your intent.
